# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Claxon Design Co. — Web Design & Development
email: adam@claxondesign.co
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
keywords: fort myers creative agency, fort myers digital agency, fort myers branding, fort myers web design, digital creative agency, fort myers design agency, web design fort myers
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adamclaxon
github_username:  adamclaxon

# Build settings
sass:
  style: compressed
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  lab:
    output: true
    permalink: /lab/:title/
  portfolio:
    permalink: /work/:title/
    output: true

defaults:
  - scope:
      path: ""
      type: "lab"
    values:
      layout: lab
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: portfolio

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
